### ISSUE TITLE
Loading articles without grouping them on top

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#20]
Hello, when I have a lot of unread articles, interface is a little laggy but readable. But is there a way to make sure that when we don't use the "auto load all articles" setting, articles won't go on top when scrolling (and thereby be read when using the mark as read on scroll, even with the gap option enabled (the gap disappears when new articles are loaded while scrolling)) ?Thank you !

**Comment by soufianesakhi** [comment]
Do you have sorting enabled ? Or group hot to top enabled ?
If so, the mark as read on scroll will not be possible when disabling the auto load all articles because you are already near the end of the page, so when new articles are loaded, all the articles will be resorted to keep a consistent sorting.
