### ISSUE TITLE
Filter duplicates (and marking them as read)

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#32]
Hello,

That feature (inspired by Inoreader) could be useful ; duplicates (in unread articles) would be based on url or title, or both for example.

Thanks for your work

**Comment by soufianesakhi** [comment]
Hello,
I have waited 1 month and never received duplicate articles (either by title or url). 
I don't think this will benefit by a lot of users, sorry.

**Comment by stas00** [comment]
An option to remove duplicates by title and by url (must strip Query string too) would be very helpful. At the moment I resort to sorting by title so that it's easy to skip duplicates as they end up listed as a group - but that means I can't sort by importance or other things.
There are hundreds of votes for this feature in feedly, though they won't implement it: https://feedly.uservoice.com/forums/192636-suggestions/suggestions/3745136-remove-duplicates
A great plugin - thank you, Soufiane

**Comment by stas00** [comment]
Your filter duplicates works great, Soufiane - Thank you for implementing that.

I have a more complicated request of the same. I use feedly to aggregate quite a few sources a few of which are aggregates themselves. So dups are a big problem due to the overlap. Your new feature works on the current unread items, but the next day I get a lot of duplicates from the previous day or two. Would it be complicated to keep a track of the items from previous days and not show those duplicates either? I'd say perhaps a sliding window of one week would take care of most such duplicates.

Thank you.

**Comment by soufianesakhi** [comment]
Can you test the version 3.12.1 ?

**Comment by stas00** [comment]
Thank you for implementing this feature, Souflane.

I enabled:
  Enable cross checking with persistence up to [3] days [x]

it will take me a few days to validate it due to the nature of this feature.

**Comment by soufianesakhi** [comment]
You're welcome :)

**Comment by mocards1776** [comment]
Sorry, I'm new to all of this...and blown away by all of your knowledge...but I got here by searching for a way to eliminate duplicate articles from different sources. How do I add the script to Feedly? Can it apply to the app? Thanks and sorry for the stupid questions.

**Comment by soufianesakhi** [comment]
# Installation

You can install only on browsers as an extension for [Google Chrome](https://chrome.google.com/webstore/detail/feedly-filtering-and-sort/anknmaofbemimfabppdffklbfiecikgo) or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/feedly_filtering_and_sorting/).

You can also install a [script](https://greasyfork.org/en/scripts/20483-feedly-filtering-and-sorting) version using user script managers such as Tampermonkey or Violentmonkey.

The mobile app is not supported.

# Duplicates across multiple sources
You can enable the option (in Advanced controls) to cross filter duplicates using a sliding window:
The duplicates will be checked across all subscriptions and categories against current articles and stored articles. The url and title of all articles published less then the configured days will be stored locally (sync not supported).
![menu_advanced](https://user-images.githubusercontent.com/17222854/40889898-6af2faec-676e-11e8-80e7-9a77ca8ce5ba.PNG)
